name: Main

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: [ "1.63", "1.64" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub container registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and optionally push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ matrix.version }}
          build-args: |
            rclone_version=${{ matrix.version }}